// data.js
window.characters = [
  {
    name: "グレイッシュブルー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/brume.png",
    selectedMindset: null,
    id: 0,
  },
  {
    name: "ベリル",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/beryl.png",
    selectedMindset: null,
    id: 1,
  },
  {
    name: "コルヴス",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/corvus.png",
    selectedMindset: null,
    id: 2,
  },
  {
    name: "ルブシカ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/rubuska.png",
    selectedMindset: null,
    id: 3,
  },
  {
    name: "カローン",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/charon.png",
    selectedMindset: null,
    id: 4,
  },
  {
    name: "センティネル",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/sentinel.png",
    selectedMindset: null,
    id: 5,
  },
  {
    name: "モルダー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/moldir.png",
    selectedMindset: null,
    id: 6,
  },
  {
    name: "ウルリッヒ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/ulrich.png",
    selectedMindset: null,
    id: 7,
  },
  {
    name: "ノーティカ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/nautika.png",
    selectedMindset: null,
    id: 8,
  },
  {
    name: "カサンドラ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/kassandra.png",
    selectedMindset: null,
    id: 9,
  },
  {
    name: "エツィオ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/ezio.png",
    selectedMindset: null,
    id: 10,
  },
  {
    name: "カイパリーナ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/kiperina.png",
    selectedMindset: null,
    id: 11,
  },
  {
    name: "サーベス",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/hissabeth.png",
    selectedMindset: null,
    id: 12,
  },
  {
    name: "エル･アレフ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/aleph.png",
    selectedMindset: null,
    id: 13,
  },
  {
    name: "レコレータ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/recoleta.png",
    selectedMindset: null,
    id: 14,
  },
  {
    name: "ノワール",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/noire.png",
    selectedMindset: null,
    id: 15,
  },
  {
    name: "梁月",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/liang.png",
    selectedMindset: null,
    id: 16,
  },
  {
    name: "トゥトゥイ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/fatutu.png",
    selectedMindset: null,
    id: 17,
  },
  {
    name: "バルカローラ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/barcarola.png",
    selectedMindset: null,
    id: 18,
  },
  {
    name: "パタパタペーパー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/flutterpage.png",
    selectedMindset: null,
    id: 19,
  },
  {
    name: "ヴィロー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/willow.png",
    selectedMindset: null,
    id: 20,
  },
  {
    name: "ロペラ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/lopera.png",
    selectedMindset: null,
    id: 21,
  },
  {
    name: "アンジョナナ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/anjonala.png",
    selectedMindset: null,
    id: 22,
  },
  {
    name: "アルゴス",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/argus.png",
    selectedMindset: null,
    id: 23,
  },
  {
    name: "チューズデー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/tuesday.png",
    selectedMindset: null,
    id: 24,
  },
  {
    name: "J",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Joe.png",
    selectedMindset: null,
    id: 25,
  },
  {
    name: "マーキュリア",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/mercuria.png",
    selectedMindset: null,
    id: 26,
  },
  {
    name: "カカニア",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/kakania.png",
    selectedMindset: null,
    id: 27,
  },
  {
    name: "センメルワイス",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["血薪"],
    img: "images/semmelweis.png",
    selectedMindset: null,
    id: 28,
  },
  {
    name: "ルーシー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["電力"],
    img: "images/lucy.png",
    selectedMindset: null,
    id: 29,
  },
  {
    name: "スヴィスティ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/windsong.png",
    selectedMindset: null,
    id: 30,
  },
  {
    name: "ヴィラ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["回復"],
    img: "images/Вила.png",
    selectedMindset: null,
    id: 31,
  },
  {
    name: "マーカス",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["S強化"],
    img: "images/marcus.png",
    selectedMindset: null,
    id: 32,
  },
  {
    name: "イゾルデ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/izolde.png",
    selectedMindset: null,
    id: 33,
  },
  {
    name: "葛天",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["陣法"],
    img: "images/getian.png",
    selectedMindset: null,
    id: 34,
  },
  {
    name: "曲娘",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["追撃"],
    img: "images/jinniangzi.png",
    selectedMindset: null,
    id: 35,
  },
  {
    name: "エズラ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["血薪", "電力"],
    img: "images/ezra.png",
    selectedMindset: null,
    id: 36,
  },
  {
    name: "カエンボク",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/spathodea.png",
    selectedMindset: null,
    id: 37,
  },
  {
    name: "6",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/six.png",
    selectedMindset: null,
    id: 38,
  },
  {
    name: "37",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/thirtyseven.png",
    selectedMindset: null,
    id: 39,
  },
  {
    name: "シャーマィン",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["ULT"],
    img: "images/shamane.png",
    selectedMindset: null,
    id: 40,
  },
  {
    name: "カーラ･ボナー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/BlackDwarf.png",
    selectedMindset: null,
    id: 41,
  },
  {
    name: "ジェシカ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["石化", "中毒"],
    img: "images/changeling.png",
    selectedMindset: null,
    id: 42,
  },
  {
    name: "トゥースフェアリー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/tooth.png",
    selectedMindset: null,
    id: 43,
  },
  {
    name: "ピクルス",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["強化"],
    img: "images/Pickles.png",
    selectedMindset: null,
    id: 44,
  },
  {
    name: "メラニア",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["MP"],
    img: "images/Melania.png",
    selectedMindset: null,
    id: 45,
  },
  {
    name: "ナイト",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Knight.png",
    selectedMindset: null,
    id: 46,
  },
  {
    name: "ニューバベル",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["シールド"],
    img: "images/NewBabel.png",
    selectedMindset: null,
    id: 47,
  },
  {
    name: "エターニティ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["自傷", "血薪"],
    img: "images/Eternity.png",
    selectedMindset: null,
    id: 48,
  },
  {
    name: "メディスンポケット",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["回復"],
    img: "images/Medicine.png",
    selectedMindset: null,
    id: 49,
  },
  {
    name: "ケントゥリオン",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["MP"],
    img: "images/Centurion.png",
    selectedMindset: null,
    id: 50,
  },
  {
    name: "ボイジャー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["啓示"],
    img: "images/Voyager.png",
    selectedMindset: null,
    id: 51,
  },
  {
    name: "リーリャ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["追撃", "弾丸"],
    img: "images/Lilya.png",
    selectedMindset: null,
    id: 52,
  },
  {
    name: "レグルス",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["啓示"],
    img: "images/Regulus.png",
    selectedMindset: null,
    id: 53,
  },
  {
    name: "リー･アンアン",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["S強化"],
    img: "images/lee.png",
    selectedMindset: null,
    id: 54,
  },
  {
    name: "サザビー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["回復"],
    img: "images/Sotheby.png",
    selectedMindset: null,
    id: 55,
  },
  {
    name: "ドルーヴィスIII",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["石化", "本源"],
    img: "images/Druvis.png",
    selectedMindset: null,
    id: 56,
  },
  {
    name: "もぐナッツ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/fairchild.png",
    selectedMindset: null,
    id: 57,
  },
  {
    name: "アレクシオス",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/alexios.png",
    selectedMindset: null,
    id: 58,
  },
  {
    name: "ネイムデー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/nameday.png",
    selectedMindset: null,
    id: 59,
  },
  {
    name: "ロガーヘッド",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/loggerhead.png",
    selectedMindset: null,
    id: 60,
  },
  {
    name: "つば広ハット",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/brimley.png",
    selectedMindset: null,
    id: 61,
  },
  {
    name: "ダンカン",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/duncan.png",
    selectedMindset: null,
    id: 62,
  },
  {
    name: "メェプル",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/barbara.png",
    selectedMindset: null,
    id: 63,
  },
  {
    name: "ローレライ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/lorelei.png",
    selectedMindset: null,
    id: 64,
  },
  {
    name: "アヴグスト",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/авксивий.png",
    selectedMindset: null,
    id: 65,
  },
  {
    name: "エニセイ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/енисей.png",
    selectedMindset: null,
    id: 66,
  },
  {
    name: "サンド･フランネル",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/flannel.png",
    selectedMindset: null,
    id: 67,
  },
  {
    name: "ウル",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/ulu.png",
    selectedMindset: null,
    id: 68,
  },
  {
    name: "カンジーラ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Kanjira.png",
    selectedMindset: null,
    id: 69,
  },
  {
    name: "ホラーペディア",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/horropedia.png",
    selectedMindset: null,
    id: 70,
  },
  {
    name: "ジェイミー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/blonney.png",
    selectedMindset: null,
    id: 71,
  },
  {
    name: "ディガー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Diggers.png",
    selectedMindset: null,
    id: 72,
  },
  {
    name: "マチルダ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["啓示"],
    img: "images/Matilda.png",
    selectedMindset: null,
    id: 73,
  },
  {
    name: "カシャパシャ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Click.png",
    selectedMindset: null,
    id: 74,
  },
  {
    name: "X",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/X.png",
    selectedMindset: null,
    id: 75,
  },
  {
    name: "バルーンパーティー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/BalloonParty.png",
    selectedMindset: null,
    id: 76,
  },
  {
    name: "ソネット",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Sonetto.png",
    selectedMindset: null,
    id: 77,
  },
  {
    name: "ネクロ･ロギスト",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Necrologist.png",
    selectedMindset: null,
    id: 78,
  },
  {
    name: "パミエ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Dikke.png",
    selectedMindset: null,
    id: 79,
  },
  {
    name: "スイートハート",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Sweetheart.png",
    selectedMindset: null,
    id: 80,
  },
  {
    name: "テナント",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["バレット"],
    img: "images/Tennant.png",
    selectedMindset: null,
    id: 81,
  },
  {
    name: "チャーリー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Charlie.png",
    selectedMindset: null,
    id: 82,
  },
  {
    name: "ベビーブルー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/BabyBlue.png",
    selectedMindset: null,
    id: 83,
  },
  {
    name: "コーンブルメ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    madness: ["デバフ"],
    img: "images/Bkornblume.png",
    selectedMindset: null,
    id: 84,
  },
  {
    name: "五色月",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Satsuki.png",
    selectedMindset: null,
    id: 85,
  },
  {
    name: "ホワイトラム",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/whiterum.png",
    selectedMindset: null,
    id: 86,
  },
  {
    name: "ポルターガイスト",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Poltergeist.png",
    selectedMindset: null,
    id: 87,
  },
  {
    name: "メスメル･Jr",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Mesmer.png",
    selectedMindset: null,
    id: 88,
  },
  {
    name: "クリスタッロ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Cristallo.png",
    selectedMindset: null,
    id: 89,
  },
  {
    name: "モントリヒト",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Mondlicht.png",
    selectedMindset: null,
    id: 90,
  },
  {
    name: "ミス･モアッサン",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Moissan.png",
    selectedMindset: null,
    id: 91,
  },
  {
    name: "パヴィア",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Pavia.png",
    selectedMindset: null,
    id: 92,
  },
  {
    name: "ニック･ボトム",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Nick.png",
    selectedMindset: null,
    id: 93,
  },
  {
    name: "バニーバニー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Bunny.png",
    selectedMindset: null,
    id: 94,
  },
  {
    name: "APPLe",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/APPLe.png",
    selectedMindset: null,
    id: 95,
  },
  {
    name: "オリバー･フォッグ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Oliver.png",
    selectedMindset: null,
    id: 96,
  },
  {
    name: "エリック",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Erick.png",
    selectedMindset: null,
    id: 97,
  },
  {
    name: "TTT",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/TTT.png",
    selectedMindset: null,
    id: 98,
  },
  {
    name: "リトルイーグル",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Eagle.png",
    selectedMindset: null,
    id: 99,
  },
  {
    name: "ズィマー",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/зима.png",
    selectedMindset: null,
    id: 100,
  },
  {
    name: "レイビーズ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Rabies.png",
    selectedMindset: null,
    id: 101,
  },
  {
    name: "パイオニア",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Pioneer.png",
    selectedMindset: null,
    id: 102,
  },
  {
    name: "リサ&ルイス",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Twins.png",
    selectedMindset: null,
    id: 103,
  },
  {
    name: "ジョン･タイター",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/John.png",
    selectedMindset: null,
    id: 104,
  },
  {
    name: "オニオン",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Onion.png",
    selectedMindset: null,
    id: 105,
  },
  {
    name: "ベティ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Bette.png",
    selectedMindset: null,
    id: 106,
  },
  {
    name: "ダーレータッタ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Darley.png",
    selectedMindset: null,
    id: 107,
  },
  {
    name: "レイラニ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Leilani.png",
    selectedMindset: null,
    id: 108,
  },
  {
    name: "スプートニク",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Sputnik.png",
    selectedMindset: null,
    id: 109,
  },
  {
    name: "ギベオンズアイ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/aliEn.png",
    selectedMindset: null,
    id: 110,
  },
  {
    name: "ジェスター",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Fool.png",
    selectedMindset: null,
    id: 111,
  },
  {
    name: "ララ･ファウンテン",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Source.png",
    selectedMindset: null,
    id: 112,
  },
  {
    name: "ミス･ラジオ",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Radio.png",
    selectedMindset: null,
    id: 113,
  },
  {
    name: "ドア",
    level: 1,
    insight: 0,
    resonance: 1,
    statue: 0,
    owned: false,
    img: "images/Door.png",
    selectedMindset: null,
    id: 114,
  },
];
