// data.js
const characters = [
  {name: "カローン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/charon.png", selectedMindset: null"},
  {name: "センティネル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/sentinel.png", selectedMindset: null"},
  {name: "モルダー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/moldir.png", selectedMindset: null"},
  {name: "ウルリッヒ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/ulrich.png", selectedMindset: null"},
  {name: "ノーティカ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/nautika.png", selectedMindset: null"},
  {name: "カサンドラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/kassandra.png", selectedMindset: null"},
  {name: "エツィオ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/ezio.png", selectedMindset: null"},
  {name: "カイパリーナ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/kiperina.png", selectedMindset: null"},
  {name: "サーベス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/hissabeth.png", selectedMindset: null"},
  {name: "エル･アレフ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/aleph.png", selectedMindset: null"},
  {name: "レコレータ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/recoleta.png", selectedMindset: null"},
  {name: "ノワール", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/noire.png", selectedMindset: null"},
  {name: "梁月", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/liang.png", selectedMindset: null"},
  {name: "トゥトゥイ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/fatutu.png", selectedMindset: null"},
  {name: "バルカローラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/barcarola.png", selectedMindset: null"},
  {name: "パタパタペーパー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/flutterpage.png", selectedMindset: null"},
  {name: "ヴィロー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/willow.png", selectedMindset: null"},
  {name: "ロペラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/lopera.png", selectedMindset: null"},
  {name: "アンジョナナ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/anjonala.png", selectedMindset: null"},
  {name: "アルゴス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/argus.png", selectedMindset: null"},
  {name: "チューズデー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/tuesday.png", selectedMindset: null"},
  {name: "J", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Joe.png", selectedMindset: null"},
  {name: "マーキュリア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/mercuria.png", selectedMindset: null"},
  {name: "カカニア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/kakania.png", selectedMindset: null"},
  {name: "センメルワイス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["血薪"], img: "images/semmelweis.png", selectedMindset: null"},
  {name: "ルーシー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["電力"], img: "images/lucy.png", selectedMindset: null"},
  {name: "スヴィスティ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/windsong.png", selectedMindset: null"},
  {name: "ヴィラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["回復"], img: "images/Вила.png", selectedMindset: null"},
  {name: "マーカス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["S強化"], img: "images/marcus.png", selectedMindset: null"},
  {name: "イゾルデ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/izolde.png", selectedMindset: null"},
  {name: "葛天", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["陣法"], img: "images/getian.png", selectedMindset: null"},
  {name: "曲娘", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["追撃"], img: "images/jinniangzi.png", selectedMindset: null"},
  {name: "エズラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["血薪", "電力"], img: "images/ezra.png", selectedMindset: null"},
  {name: "カエンボク", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/spathodea.png", selectedMindset: null"},
  {name: "6", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/six.png", selectedMindset: null"},
  {name: "37", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/thirtyseven.png", selectedMindset: null"},
  {name: "シャーマィン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["ULT"], img: "images/shamane.png", selectedMindset: null"},
  {name: "カーラ･ボナー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/BlackDwarf.png", selectedMindset: null"},
  {name: "ジェシカ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["石化", "中毒"], img: "images/changeling.png", selectedMindset: null"},
  {name: "トゥースフェアリー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/tooth.png", selectedMindset: null"},
  {name: "ピクルス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["強化"], img: "images/Pickles.png", selectedMindset: null"},
  {name: "メラニア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["MP"], img: "images/Melania.png", selectedMindset: null"},
  {name: "ナイト", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Knight.png", selectedMindset: null"},
  {name: "ニューバベル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["シールド"], img: "images/NewBabel.png", selectedMindset: null"},
  {name: "エターニティ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["自傷", "血薪"], img: "images/Eternity.png", selectedMindset: null"},
  {name: "メディスンポケット", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["回復"], img: "images/Medicine.png", selectedMindset: null"},
  {name: "ケントゥリオン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["MP"], img: "images/Centurion.png", selectedMindset: null"},
  {name: "ボイジャー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["啓示"], img: "images/Voyager.png", selectedMindset: null"},
  {name: "リーリャ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["追撃", "弾丸"], img: "images/Lilya.png", selectedMindset: null"},
  {name: "レグルス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["啓示"], img: "images/Regulus.png", selectedMindset: null"},
  {name: "リー･アンアン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["S強化"], img: "images/lee.png", selectedMindset: null"},
  {name: "サザビー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["回復"], img: "images/Sotheby.png", selectedMindset: null"},
  {name: "ドルーヴィスIII", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["石化", "本源"], img: "images/Druvis.png", selectedMindset: null"},
  //☆5
  {name: "もぐナッツ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/fairchild.png", selectedMindset: null"},
  {name: "アレクシオス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/alexios.png", selectedMindset: null"},
  {name: "ネイムデー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/nameday.png", selectedMindset: null"},
  {name: "ロガーヘッド", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/loggerhead.png", selectedMindset: null"},
  {name: "つば広ハット", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/brimley.png", selectedMindset: null"},
  {name: "ダンカン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/duncan.png", selectedMindset: null"},
  {name: "メェプル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/barbara.png", selectedMindset: null"},
  {name: "ローレライ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/lorelei.png", selectedMindset: null"},
  {name: "アヴグスト", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/авксивий.png", selectedMindset: null"},
  {name: "エニセイ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/енисей.png", selectedMindset: null"},
  {name: "サンド･フランネル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/flannel.png", selectedMindset: null"},
  {name: "ウル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/ulu.png", selectedMindset: null"},
  {name: "カンジーラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Kanjira.png", selectedMindset: null"},
  {name: "ホラーペディア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/horropedia.png", selectedMindset: null"},
  {name: "ジェイミー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/blonney.png", selectedMindset: null"},
  {name: "ディガー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Diggers.png", selectedMindset: null"},
  {name: "マチルダ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["啓示"], img: "images/Matilda.png", selectedMindset: null"},
  {name: "カシャパシャ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Click.png", selectedMindset: null"},
  {name: "X", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/X.png", selectedMindset: null"},
  {name: "バルーンパーティー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/BalloonParty.png", selectedMindset: null"},
  {name: "ソネット", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Sonetto.png", selectedMindset: null"},
  {name: "ネクロ･ロギスト", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Necrologist.png", selectedMindset: null"},
  {name: "パミエ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Dikke.png", selectedMindset: null"},
  {name: "スイートハート", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Sweetheart.png", selectedMindset: null"},
  {name: "テナント", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["バレット"], img: "images/Tennant.png", selectedMindset: null"},
  {name: "チャーリー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Charlie.png", selectedMindset: null"},
  {name: "ベビーブルー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/BabyBlue.png", selectedMindset: null"},
  {name: "コーンブルメ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, madness: ["デバフ"], img: "images/Bkornblume.png", selectedMindset: null"},
  {name: "五色月", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Satsuki.png", selectedMindset: null"},
  //☆4
  {name: "ホワイトラム", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/whiterum.png", selectedMindset: null"},
  {name: "ポルターガイスト", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Poltergeist.png", selectedMindset: null"},
  {name: "メスメル･Jr", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Mesmer.png", selectedMindset: null"},
  {name: "クリスタッロ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Cristallo.png", selectedMindset: null"},
  {name: "モントリヒト", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Mondlicht.png", selectedMindset: null"},
  {name: "ミス･モアッサン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Moissan.png", selectedMindset: null"},
  {name: "パヴィア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Pavia.png", selectedMindset: null"},
  {name: "ニック･ボトム", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Nick.png", selectedMindset: null"},
  {name: "バニーバニー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Bunny.png", selectedMindset: null"},
  {name: "APPLe", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/APPLe.png", selectedMindset: null"},
  {name: "オリバー･フォッグ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Oliver.png", selectedMindset: null"},
  {name: "エリック", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Erick.png", selectedMindset: null"},
  {name: "TTT", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/TTT.png", selectedMindset: null"},
  {name: "リトルイーグル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Eagle.png", selectedMindset: null"},
  {name: "ズィマー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/зима.png", selectedMindset: null"},
  {name: "レイビーズ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Rabies.png", selectedMindset: null"},
  //☆3
  {name: "パイオニア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Pioneer.png", selectedMindset: null"},
  {name: "リサ&ルイス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Twins.png", selectedMindset: null"},
  {name: "ジョン･タイター", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/John.png", selectedMindset: null"},
  {name: "オニオン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Onion.png", selectedMindset: null"},
  {name: "ベティ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Bette.png", selectedMindset: null"},
  {name: "ダーレータッタ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Darley.png", selectedMindset: null"},
  {name: "レイラニ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Leilani.png", selectedMindset: null"},
  {name: "スプートニク", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Sputnik.png", selectedMindset: null"},
  {name: "ギベオンズアイ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/aliEn.png", selectedMindset: null"},
  {name: "ジェスター", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Fool.png", selectedMindset: null", selectedMindset: null"},
  {name: "ララ･ファウンテン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Source.png", selectedMindset: null"},
  {name: "ミス･ラジオ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Radio.png", selectedMindset: null"},
  {name: "ドア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Door.png", selectedMindset: null"}
];

const mindsets = [
    {name: "細流に流れ込んで", level: 1, amplify: 0, owned: false, img: "images/sairyuninagare.png"},
    {name: "帰郷の追悼", level: 1, amplify: 0, owned: false, img: "images/kikyounotuitou.png"},
    {name: "ふとしたきらめき", level: 1, amplify: 0, owned: false, img: "images/hutosita.png"},
    {name: "家族の導き手", level: 1, amplify: 0, owned: false, img: "images/kazokunomitibikite.png"},
    {name: "心の墓碑銘", level: 1, amplify: 0, owned: false, img: "images/kokoronobohimei.png"},
    {name: "叙事詩の終焉", level: 1, amplify: 0, owned: false, img: "images/jozisinosyuen.png"},
    {name: "黄昏に響く鐘", level: 1, amplify: 0, owned: false, img: "images/tasogarenihibiku.png"},
    {name: "春の足取り", level: 1, amplify: 0, owned: false, img: "images/harunoasidori.png"},
    {name: "終わらないQ&A", level: 1, amplify: 0, owned: false, img: "images/owaranaiqa.png"},
    {name: "脳の牢獄", level: 1, amplify: 0, owned: false, img: "images/nounorougoku.png"},
    {name: "最後のダイス", level: 1, amplify: 0, owned: false, img: "images/saigonodice.png"},
    {name: "夢づくりのリハーサル", level: 1, amplify: 0, owned: false, img: "images/yumedukurino.png"},
    {name: "直ちに応答せよ", level: 1, amplify: 0, owned: false, img: "images/tadatinioutouseyo.png"},
    {name: "貝殻のひび割れ", level: 1, amplify: 0, owned: false, img: "images/kaigaranohibiware.png"},
    {name: "別れの変奏曲", level: 1, amplify: 0, owned: false, img: "images/wakarenohensou.png"},
    {name: "秒針の住み処", level: 1, amplify: 0, owned: false, img: "images/byousinnosumidokoro.png"},
    {name: "ささやかな願い", level: 1, amplify: 0, owned: false, img: "images/sasayakananegai.png"},
    {name: "ノンリズムジャンプ", level: 1, amplify: 0, owned: false, img: "images/nonrhythm.png"},
    {name: "三度目の信頼", level: 1, amplify: 0, owned: false, img: "images/sandomenosinrai.png"},
    {name: "愛の本質", level: 1, amplify: 0, owned: false, img: "images/ainohonsitu.png"},
    {name: "夜の奥深くへと", level: 1, amplify: 0, owned: false, img: "images/yorunookuhukaku.png"},
    {name: "メイドは見た", level: 1, amplify: 0, owned: false, img: "images/meidohamita.png"},
    {name: "流れ行く泉のように", level: 1, amplify: 0, owned: false, img: "images/nagareyukuizumi.png"},
    {name: "最奥より", level: 1, amplify: 0, owned: false, img: "images/saiouyori.png"},
    {name: "語られざる軽さ", level: 1, amplify: 0, owned: false, img: "images/katararezaru.png"},
    {name: "勇ましい者の言葉", level: 1, amplify: 0, owned: false, img: "images/isamasimono.png"},
    {name: "前進の足音", level: 1, amplify: 0, owned: false, img: "images/zensinnoasioto.png"},
    {name: "近づく雨の音", level: 1, amplify: 0, owned: false, img: "images/tikadukuameno.png"},
    {name: "証明の試み", level: 1, amplify: 0, owned: false, img: "images/syoumeinokokoromi.png"},
    {name: "夜は明ける", level: 1, amplify: 0, owned: false, img: "images/yohaakeru.png"},
    {name: "もうひとつの物語", level: 1, amplify: 0, owned: false, img: "images/mouhitotuno.png"},
    {name: "狭いドアをノックして", level: 1, amplify: 0, owned: false, img: "images/semaidoawo.png"},
    {name: "目下に新事なし", level: 1, amplify: 0, owned: false, img: "images/mokkanisinzi.png"},
    {name: "四方城の外にて", level: 1, amplify: 0, owned: false, img: "images/sihoujou.png"},
    {name: "長い夜話", level: 1, amplify: 0, owned: false, img: "images/nagaiyawa.png"},
    {name: "バランスに注意", level: 1, amplify: 0, owned: false, img: "images/baransunityui.png"},
    {name: "沈黙と憧れ", level: 1, amplify: 0, owned: false, img: "images/tinmokutoakogare.png"},
    {name: "測定可能な心", level: 1, amplify: 0, owned: false, img: "images/sokuteikanou.png"},
    {name: "おとぎの国の外", level: 1, amplify: 0, owned: false, img: "images/otoginokuni.png"},
    {name: "娯楽至上", level: 1, amplify: 0, owned: false, img: "images/gorakusijou.png"},
    {name: "必要な記録", level: 1, amplify: 0, owned: false, img: "images/hituyounakiroku.png"},
    {name: "好奇心の塊", level: 1, amplify: 0, owned: false, img: "images/koukisinnokatamari.png"},
    {name: "万雷の拍手", level: 1, amplify: 0, owned: false, img: "images/banrainohakusyu.png"},
    {name: "夜を冒涜する者", level: 1, amplify: 0, owned: false, img: "images/yoruwoboutoku.png"},
    {name: "二度目の人生", level: 1, amplify: 0, owned: false, img: "images/nidomenozinsei.png"},
    {name: "ホップスコッチ", level: 1, amplify: 0, owned: false, img: "images/hopsukotti.png"},
    {name: "美しい新世界", level: 1, amplify: 0, owned: false, img: "images/utukusisinsekai.png"},
    {name: "道端のほこり", level: 1, amplify: 0, owned: false, img: "images/mitibatanohokori.png"},
    {name: "懐かしい歌、新しいメロディー", level: 1, amplify: 0, owned: false, img: "images/natukasiuta.png"},
    {name: "舞台裏の注釈", level: 1, amplify: 0, owned: false, img: "images/butaiuranotyusyaku.png"},
    {name: "除霊パートナー", level: 1, amplify: 0, owned: false, img: "images/joreipartner.png"},
    {name: "ベルト･イット･アウト", level: 1, amplify: 0, owned: false, img: "images/beltitout.png"},
    {name: "迷道の外", level: 1, amplify: 0, owned: false, img: "images/meidounosoto.png"},
    {name: "心に刻みこんだもの", level: 1, amplify: 0, owned: false, img: "images/kokoronikizamikonda.png"},
    {name: "現象の中に落ちて", level: 1, amplify: 0, owned: false, img: "images/gensyounonakaniotite.png"},
    {name: "生気に満ちた物語", level: 1, amplify: 0, owned: false, img: "images/seikinimitita.png"},
    {name: "知られざる芸術", level: 1, amplify: 0, owned: false, img: "images/sirarezarugeijutu.png"},
    {name: "自業自得", level: 1, amplify: 0, owned: false, img: "images/zigouzitoku.png"},
    {name: "デプレッション", level: 1, amplify: 0, owned: false, img: "images/depuressyon.png"},
    {name: "ウォーク･アローン", level: 1, amplify: 0, owned: false, img: "images/walkalone.png"},
    {name: "影にて", level: 1, amplify: 0, owned: false, img: "images/kagenite.png"},
    {name: "沈黙の眼差し", level: 1, amplify: 0, owned: false, img: "images/tinmokunomanazasi.png"},
    {name: "夜な夜な", level: 1, amplify: 0, owned: false, img: "images/yonayona.png"},
    {name: "歯車の外", level: 1, amplify: 0, owned: false, img: "images/hagurumanosoto.png"},
    {name: "昨日の出来事", level: 1, amplify: 0, owned: false, img: "images/kinounodekigoto.png"},
    {name: "新たなページ", level: 1, amplify: 0, owned: false, img: "images/aratanapage.png"},
    {name: "ティータイム", level: 1, amplify: 0, owned: false, img: "images/teatime.png"},
    {name: "苦しい旅の途中", level: 1, amplify: 0, owned: false, img: "images/kurusiitabinototyu.png"},
    {name: "いざ出航", level: 1, amplify: 0, owned: false, img: "images/izasyukkou.png"},
    {name: "アブサーディティ･ライフ", level: 1, amplify: 0, owned: false, img: "images/abusadexitexi.png"},
    {name: "サティスファイド･イーター", level: 1, amplify: 0, owned: false, img: "images/satexisufaido.png"},
    {name: "楽しげな笑い声", level: 1, amplify: 0, owned: false, img: "images/tanosigenawaraigoe.png"},
    {name: "自由な心", level: 1, amplify: 0, owned: false, img: "images/ziyunakokoro.png"},
    {name: "遥かなる前途", level: 1, amplify: 0, owned: false, img: "images/harukanaruzento.png"},
    {name: "午後の休憩", level: 1, amplify: 0, owned: false, img: "images/gogonokyukei.png"},
    {name: "むき出しの真実", level: 1, amplify: 0, owned: false, img: "images/mukidasinosinzitu.png"},
    {name: "気ままに", level: 1, amplify: 0, owned: false, img: "images/kimamani.png"},
    {name: "明日も同じ", level: 1, amplify: 0, owned: false, img: "images/asumoonazi.png"},
    {name: "思いを馳せて", level: 1, amplify: 0, owned: false, img: "images/omoiwohasete.png"},
    {name: "静謐", level: 1, amplify: 0, owned: false, img: "images/seihitu.png"},
    {name: "緑毒", level: 1, amplify: 0, owned: false, img: "images/ryokudoku.png"},
    {name: "貪欲", level: 1, amplify: 0, owned: false, img: "images/donyoku.png"},
    {name: "祟奉", level: 1, amplify: 0, owned: false, img: "images/tatari.png"},
    {name: "航海", level: 1, amplify: 0, owned: false, img: "images/koukai.png"},
    {name: "歓声", level: 1, amplify: 0, owned: false, img: "images/kannsei.png"},
    {name: "無感覚", level: 1, amplify: 0, owned: false, img: "images/mukankaku.png"},
    {name: "蒙昧", level: 1, amplify: 0, owned: false, img: "images/moumai.png"},
    {name: "軽蔑", level: 1, amplify: 0, owned: false, img: "images/keibetu.png"},
    {name: "鬱然", level: 1, amplify: 0, owned: false, img: "images/utuzen.png"},
    {name: "喪失", level: 1, amplify: 0, owned: false, img: "images/sousitu.png"}
];
