// data.js
const characters = [
  {name: "センティネル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/sentinel.png"},
  {name: "モルダー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/moldir.png"},
  {name: "ウルリッヒ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/ulrich.png"},
  {name: "ノーティカ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/nautika.png"},
  {name: "カサンドラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/kassandra.png"},
  {name: "エツィオ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/ezio.png"},
  {name: "カイパリーナ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/kiperina.png"},
  {name: "サーベス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/hissabeth.png"},
  {name: "エル･アレフ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/aleph.png"},
  {name: "レコレータ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/recoleta.png"},
  {name: "ノワール", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/noire.png"},
  {name: "梁月", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/liang.png"},
  {name: "トゥトゥイ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/fatutu.png"},
  {name: "バルカローラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/barcarola.png"},
  {name: "パタパタペーパー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/flutterpage.png"},
  {name: "ヴィロー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/willow.png"},
  {name: "ロペラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/lopera.png"},
  {name: "アンジョナナ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/anjonala.png"},
  {name: "アルゴス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/argus.png"},
  {name: "チューズデー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/tuesday.png"},
  {name: "J", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/joe.png"},
  {name: "マーキュリア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/mercuria.png"},
  {name: "カカニア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/kakania.png"},
  {name: "センメルワイス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/semmelweis.png"},
  {name: "ルーシー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/lucy.png"},
  {name: "スヴィスティ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/windsong.png"},
  {name: "ヴィラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Вила.png"},
  {name: "マーカス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/marcus.png"},
  {name: "イゾルデ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/izolde.png"},
  {name: "葛天", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/getian.png"},
  {name: "曲娘", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/jinniangzi.png"},
  {name: "エズラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/ezra.png"},
  {name: "カエンボク", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/spathodea.png"},
  {name: "6", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/six.png"},
  {name: "37", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/thirtyseven.png"},
  {name: "シャーマィン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/shamane.png"},
  {name: "カーラ･ボナー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Blackdwarf.png"},
  {name: "ジェシカ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/changeling.png"},
  {name: "トゥースフェアリー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/tooth.png"},
  {name: "ピクルス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Pickles.png"},
  {name: "メラニア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Melania.png"},
  {name: "ナイト", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Knight.png"},
  {name: "ニューバベル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Newbabel.png"},
  {name: "エターニティ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Eternity.png"},
  {name: "メディスンポケット", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/medicine.png"},
  {name: "ケントゥリオン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Centurion.png"},
  {name: "ボイジャー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Voyager.png"},
  {name: "リーリャ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Lilya.png"},
  {name: "レグルス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Regulus.png"},
  {name: "リー･アンアン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/lee.png"},
  {name: "サザビー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Sotheby.png"},
  {name: "ドルーヴィスIII", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Druvis.png"},
  //☆5
  {name: "もぐナッツ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/fairchild.png"},
  {name: "アレクシオス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/alexios.png"},
  {name: "ネイムデー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/nameday.png"},
  {name: "ロガーヘッド", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/loggerhead.png"},
  {name: "つば広ハット", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/brimley.png"},
  {name: "ダンカン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/duncan.png"},
  {name: "メェプル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/barbara.png"},
  {name: "ローレライ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/lorelei.png"},
  {name: "アヴグスト", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/авксивий.png"},
  {name: "エニセイ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/енисей.png"},
  {name: "サンド･フランネル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/flannel.png"},
  {name: "ウル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/ulu.png"},
  {name: "カンジーラ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/kanjira.png"},
  {name: "ホラーペディア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/horropedia.png"},
  {name: "ジェイミー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/blonney.png"},
  {name: "ディガー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/diggers.png"},
  {name: "マチルダ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/matilda.png"},
  {name: "カシャパシャ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/click.png"},
  {name: "X", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/X.png"},
  {name: "バルーンパーティー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/balloonpayty.png"},
  {name: "ソネット", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/sonetto.png"},
  {name: "ネクロ･ロギスト", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/necrologist.png"},
  {name: "パミエ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/dikke.png"},
  {name: "スイートハート", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/sweetheart.png"},
  {name: "テナント", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/tennant.png"},
  {name: "チャーリー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/charlie.png"},
  {name: "ベビーブルー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/babyblue.png"},
  {name: "コーンブルメ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/bkornblume.png"},
  {name: "五色月", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/satsuki.png"},
  //☆4
  {name: "ホワイトラム", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/whiterum.png"},
  {name: "ポルターガイスト", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/poltergeist.png"},
  {name: "メスメル･Jr", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/mesmer.png"},
  {name: "クリスタッロ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/cristallo.png"},
  {name: "モントリヒト", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/mondlicht.png"},
  {name: "ミス･モアッサン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/moissan.png"},
  {name: "パヴィア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/pavia.png"},
  {name: "ニック･ボトム", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/nick.png"},
  {name: "バニーバニー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/bunny.png"},
  {name: "APPLe", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/APPLe.png"},
  {name: "オリバー･フォッグ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Oliver.png"},
  {name: "エリック", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Erick.png"},
  {name: "TTT", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/TTT.png"},
  {name: "リトルイーグル", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Eagle.png"},
  {name: "ズィマー", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/зима.png"},
  {name: "レイビーズ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Rabies.png"},
  //☆3
  {name: "パイオニア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Pioneer.png"},
  {name: "リサ&ルイス", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Twins.png"},
  {name: "ジョン･タイター", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/John.png"},
  {name: "オニオン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Onion.png"},
  {name: "ベティ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Bette.png"},
  {name: "ダーレータッタ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Darley.png"},
  {name: "レイラニ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Leilani.png"},
  {name: "スプートニク", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Sputnik.png"},
  {name: "ギベオンズアイ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/aliEn.png"},
  {name: "ジェスター", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Fool.png"},
  {name: "ララ･ファウンテン", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Source.png"},
  {name: "ミス･ラジオ", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Radio.png"},
  {name: "ドア", level: 1, insight: 0, resonance: 1, statue: 0, owned: false, img: "images/Door.png"}
];

const mindsets = [
    {name: "細流に流れ込んで", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "帰郷の追悼", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "ふとしたきらめき", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "家族の導き手", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "心の墓碑銘", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "叙事詩の終焉", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "黄昏に響く鐘", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "春の足取り", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "終わらないQ&A", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "脳の牢獄", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "最後のダイス", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "夢づくりのリハーサル", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "直ちに応答せよ", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "貝殻のひび割れ", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "別れの変奏曲", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "秒針の住み処", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "ささやかな願い", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "ノンリズムジャンプ", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "三度目の信頼", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "愛の本質", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "夜の奥深くへと", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "メイドは見た", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "流れ行く泉のように", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "最奥より", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "語られざる軽さ", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "勇ましい者の言葉", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "前進の足音", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "近づく雨の音", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "証明の試み", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "夜は明ける", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "もうひとつの物語", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "狭いドアをノックして", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "目下に新事なし", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "四方城の外にて", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "長い夜話", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "バランスに注意", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "沈黙と憧れ", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "測定可能な心", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "おとぎの国の外", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "娯楽至上", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "必要な記録", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "好奇心の塊", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "万雷の拍手", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "夜を冒涜する者", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "二度目の人生", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "ホップスコッチ", level: 1, amplify: 0, owned: false, img: "images/mind2.png"},
    {name: "美しい新世界", level: 1, amplify: 0, owned: false, img: "images/mind1.png"},
    {name: "道端のほこり", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "懐かしい歌、新しいメロディー", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "舞台裏の注釈", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "除霊パートナー", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "ベルト･イット･アウト", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "迷道の外", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "心に刻みこんだもの", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "現象の中に落ちて", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "生気に満ちた物語", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "知られざる芸術", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "自業自得", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "デプレッション", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "ウォーク･アローン", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "影にて", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "沈黙の眼差し", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "夜な夜な", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "歯車の外", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "昨日の出来事", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "新たなページ", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "ティータイム", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "苦しい旅の途中", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "いざ出航", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "アブサーディティ･ライフ", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "サティスファイド･イーター", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "楽しげな笑い声", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "自由な心", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "遥かなる前途", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "午後の休憩", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "むき出しの真実", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "気ままに", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "明日も同じ", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "思いを馳せて", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "静謐", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "緑毒", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "貪欲", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "祟奉", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "航海", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "歓声", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "無感覚", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "蒙昧", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "軽蔑", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "鬱然", level: 1, amplify: 0, owned: false, img: "images/.png"},
    {name: "喪失", level: 1, amplify: 0, owned: false, img: "images/.png"}
];
