const mindsets = [
  {
    name: "さすらいの即興曲",
    level: 1,
    amplify: 0,
    owned: false,
    img: "imagessasuraino.png",
  },
  {
    name: "種に囁きかけ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tanenisasayaki.png",
  },
  {
    name: "細流に流れ込んで",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sairyuninagare.png",
  },
  {
    name: "帰郷の追悼",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kikyounotuitou.png",
  },
  {
    name: "ふとしたきらめき",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/hutosita.png",
  },
  {
    name: "家族の導き手",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kazokunomitibikite.png",
  },
  {
    name: "心の墓碑銘",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kokoronobohimei.png",
  },
  {
    name: "叙事詩の終焉",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/jozisinosyuen.png",
  },
  {
    name: "黄昏に響く鐘",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tasogarenihibiku.png",
  },
  {
    name: "春の足取り",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/harunoasidori.png",
  },
  {
    name: "終わらないQ&A",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/owaranaiqa.png",
  },
  {
    name: "脳の牢獄",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nounorougoku.png",
  },
  {
    name: "最後のダイス",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/saigonodice.png",
  },
  {
    name: "夢づくりのリハーサル",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/yumedukurino.png",
  },
  {
    name: "直ちに応答せよ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tadatinioutouseyo.png",
  },
  {
    name: "貝殻のひび割れ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kaigaranohibiware.png",
  },
  {
    name: "別れの変奏曲",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/wakarenohensou.png",
  },
  {
    name: "秒針の住み処",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/byousinnosumidokoro.png",
  },
  {
    name: "ささやかな願い",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sasayakananegai.png",
  },
  {
    name: "ノンリズムジャンプ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nonrhythm.png",
  },
  {
    name: "三度目の信頼",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sandomenosinrai.png",
  },
  {
    name: "愛の本質",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/ainohonsitu.png",
  },
  {
    name: "夜の奥深くへと",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/yorunookuhukaku.png",
  },
  {
    name: "メイドは見た",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/meidohamita.png",
  },
  {
    name: "流れ行く泉のように",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nagareyukuizumi.png",
  },
  {
    name: "最奥より",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/saiouyori.png",
  },
  {
    name: "語られざる軽さ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/katararezaru.png",
  },
  {
    name: "勇ましい者の言葉",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/isamasimono.png",
  },
  {
    name: "前進の足音",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/zensinnoasioto.png",
  },
  {
    name: "近づく雨の音",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tikadukuameno.png",
  },
  {
    name: "証明の試み",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/syoumeinokokoromi.png",
  },
  {
    name: "夜は明ける",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/yohaakeru.png",
  },
  {
    name: "もうひとつの物語",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/mouhitotuno.png",
  },
  {
    name: "狭いドアをノックして",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/semaidoawo.png",
  },
  {
    name: "目下に新事なし",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/mokkanisinzi.png",
  },
  {
    name: "四方城の外にて",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sihoujou.png",
  },
  {
    name: "長い夜話",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nagaiyawa.png",
  },
  {
    name: "バランスに注意",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/baransunityui.png",
  },
  {
    name: "沈黙と憧れ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tinmokutoakogare.png",
  },
  {
    name: "測定可能な心",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sokuteikanou.png",
  },
  {
    name: "おとぎの国の外",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/otoginokuni.png",
  },
  {
    name: "娯楽至上",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/gorakusijou.png",
  },
  {
    name: "必要な記録",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/hituyounakiroku.png",
  },
  {
    name: "好奇心の塊",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/koukisinnokatamari.png",
  },
  {
    name: "万雷の拍手",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/banrainohakusyu.png",
  },
  {
    name: "夜を冒涜する者",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/yoruwoboutoku.png",
  },
  {
    name: "二度目の人生",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nidomenozinsei.png",
  },
  {
    name: "ホップスコッチ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/hopsukotti.png",
  },
  {
    name: "美しい新世界",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/utukusisinsekai.png",
  },
  {
    name: "偽物と模造品",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nisemonoto.png",
  },
  {
    name: "道端のほこり",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/mitibatanohokori.png",
  },
  {
    name: "懐かしい歌、新しいメロディー",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/natukasiuta.png",
  },
  {
    name: "舞台裏の注釈",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/butaiuranotyusyaku.png",
  },
  {
    name: "除霊パートナー",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/joreipartner.png",
  },
  {
    name: "ベルト･イット･アウト",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/beltitout.png",
  },
  {
    name: "迷道の外",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/meidounosoto.png",
  },
  {
    name: "心に刻みこんだもの",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kokoronikizamikonda.png",
  },
  {
    name: "現象の中に落ちて",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/gensyounonakaniotite.png",
  },
  {
    name: "生気に満ちた物語",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/seikinimitita.png",
  },
  {
    name: "知られざる芸術",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sirarezarugeijutu.png",
  },
  {
    name: "自業自得",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/zigouzitoku.png",
  },
  {
    name: "デプレッション",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/depuressyon.png",
  },
  {
    name: "ウォーク･アローン",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/walkalone.png",
  },
  {
    name: "影にて",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kagenite.png",
  },
  {
    name: "沈黙の眼差し",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tinmokunomanazasi.png",
  },
  {
    name: "夜な夜な",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/yonayona.png",
  },
  {
    name: "歯車の外",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/hagurumanosoto.png",
  },
  {
    name: "昨日の出来事",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kinounodekigoto.png",
  },
  {
    name: "新たなページ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/aratanapage.png",
  },
  {
    name: "ティータイム",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/teatime.png",
  },
  {
    name: "苦しい旅の途中",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kurusiitabinototyu.png",
  },
  {
    name: "いざ出航",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/izasyukkou.png",
  },
  {
    name: "アブサーディティ･ライフ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/abusadexitexi.png",
  },
  {
    name: "サティスファイド･イーター",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/satexisufaido.png",
  },
  {
    name: "楽しげな笑い声",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tanosigenawaraigoe.png",
  },
  {
    name: "自由な心",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/ziyunakokoro.png",
  },
  {
    name: "遥かなる前途",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/harukanaruzento.png",
  },
  {
    name: "午後の休憩",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/gogonokyukei.png",
  },
  {
    name: "むき出しの真実",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/mukidasinosinzitu.png",
  },
  {
    name: "気ままに",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kimamani.png",
  },
  {
    name: "明日も同じ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/asumoonazi.png",
  },
  {
    name: "思いを馳せて",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/omoiwohasete.png",
  },
  {
    name: "静謐",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/seihitu.png",
  },
  {
    name: "緑毒",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/ryokudoku.png",
  },
  {
    name: "貪欲",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/donyoku.png",
  },
  {
    name: "祟奉",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tatari.png",
  },
  {
    name: "航海",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/koukai.png",
  },
  {
    name: "歓声",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kannsei.png",
  },
  {
    name: "無感覚",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/mukankaku.png",
  },
  {
    name: "蒙昧",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/moumai.png",
  },
  {
    name: "軽蔑",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/keibetu.png",
  },
  {
    name: "鬱然",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/utuzen.png",
  },
  {
    name: "喪失",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sousitu.png",
  },
];



