window.mindsets = [
 /* {
    name: "残された者の旅",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nokosareta.png",
    id: 0,
  }, */
  {
    name: "さすらいの即興曲",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sasuraino.png",
    id: 1,
  },
  {
    name: "種に囁きかけ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tanenisasayaki.png",
    id: 2,
  },
  {
    name: "細流に流れ込んで",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sairyuninagare.png",
    id: 3,
  },
  {
    name: "帰郷の追悼",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kikyounotuitou.png",
    id: 4,
  },
  {
    name: "ふとしたきらめき",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/hutosita.png",
    id: 5,
  },
  {
    name: "家族の導き手",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kazokunomitibikite.png",
    id: 6,
  },
  {
    name: "心の墓碑銘",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kokoronobohimei.png",
    id: 7,
  },
  {
    name: "叙事詩の終焉",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/jozisinosyuen.png",
    id: 8,
  },
  {
    name: "黄昏に響く鐘",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tasogarenihibiku.png",
    id: 9,
  },
  {
    name: "春の足取り",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/harunoasidori.png",
    id: 10,
  },
  {
    name: "終わらないQ&A",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/owaranaiqa.png",
    id: 11,
  },
  {
    name: "脳の牢獄",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nounorougoku.png",
    id: 12,
  },
  {
    name: "最後のダイス",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/saigonodice.png",
    id: 13,
  },
  {
    name: "夢づくりのリハーサル",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/yumedukurino.png",
    id: 14,
  },
  {
    name: "直ちに応答せよ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tadatinioutouseyo.png",
    id: 15,
  },
  {
    name: "貝殻のひび割れ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kaigaranohibiware.png",
    id: 16,
  },
  {
    name: "別れの変奏曲",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/wakarenohensou.png",
    id: 17,
  },
  {
    name: "秒針の住み処",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/byousinnosumidokoro.png",
    id: 18,
  },
  {
    name: "ささやかな願い",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sasayakananegai.png",
    id: 19,
  },
  {
    name: "ノンリズムジャンプ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nonrhythm.png",
    id: 20,
  },
  {
    name: "三度目の信頼",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sandomenosinrai.png",
    id: 21,
  },
  {
    name: "愛の本質",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/ainohonsitu.png",
    id: 22,
  },
  {
    name: "夜の奥深くへと",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/yorunookuhukaku.png",
    id: 23,
  },
  {
    name: "メイドは見た",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/meidohamita.png",
    id: 24,
  },
  {
    name: "流れ行く泉のように",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nagareyukuizumi.png",
    id: 25,
  },
  {
    name: "最奥より",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/saiouyori.png",
    id: 26,
  },
  {
    name: "語られざる軽さ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/katararezaru.png",
    id: 27,
  },
  {
    name: "勇ましい者の言葉",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/isamasimono.png",
    id: 28,
  },
  {
    name: "前進の足音",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/zensinnoasioto.png",
    id: 29,
  },
  {
    name: "近づく雨の音",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tikadukuameno.png",
    id: 30,
  },
  {
    name: "証明の試み",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/syoumeinokokoromi.png",
    id: 31,
  },
  {
    name: "夜は明ける",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/yohaakeru.png",
    id: 32,
  },
  {
    name: "もうひとつの物語",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/mouhitotuno.png",
    id: 33,
  },
  {
    name: "狭いドアをノックして",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/semaidoawo.png",
    id: 34,
  },
  {
    name: "目下に新事なし",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/mokkanisinzi.png",
    id: 35,
  },
  {
    name: "四方城の外にて",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sihoujou.png",
    id: 36,
  },
  {
    name: "長い夜話",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nagaiyawa.png",
    id: 37,
  },
  {
    name: "バランスに注意",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/baransunityui.png",
    id: 38,
  },
  {
    name: "沈黙と憧れ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tinmokutoakogare.png",
    id: 39,
  },
  {
    name: "測定可能な心",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sokuteikanou.png",
    id: 40,
  },
  {
    name: "おとぎの国の外",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/otoginokuni.png",
    id: 41,
  },
  {
    name: "娯楽至上",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/gorakusijou.png",
    id: 42,
  },
  {
    name: "必要な記録",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/hituyounakiroku.png",
    id: 43,
  },
  {
    name: "好奇心の塊",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/koukisinnokatamari.png",
    id: 44,
  },
  {
    name: "万雷の拍手",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/banrainohakusyu.png",
    id: 45,
  },
  {
    name: "夜を冒涜する者",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/yoruwoboutoku.png",
    id: 46,
  },
  {
    name: "二度目の人生",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nidomenozinsei.png",
    id: 47,
  },
  {
    name: "ホップスコッチ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/hopsukotti.png",
    id: 48,
  },
  {
    name: "美しい新世界",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/utukusisinsekai.png",
    id: 49,
  },
/*  {
    name: "色褪せたエピタフ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/epitaf.png",
    id: 50,
  }, */
  {
    name: "偽物と模造品",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/nisemonoto.png",
    id: 51,
  },
  {
    name: "道端のほこり",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/mitibatanohokori.png",
    id: 52,
  },
  {
    name: "懐かしい歌、新しいメロディー",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/natukasiuta.png",
    id: 53,
  },
  {
    name: "舞台裏の注釈",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/butaiuranotyusyaku.png",
    id: 54,
  },
  {
    name: "除霊パートナー",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/joreipartner.png",
    id: 55,
  },
  {
    name: "ベルト･イット･アウト",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/beltitout.png",
    id: 56,
  },
  {
    name: "迷道の外",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/meidounosoto.png",
    id: 57,
  },
  {
    name: "心に刻みこんだもの",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kokoronikizamikonda.png",
    id: 58,
  },
  {
    name: "現象の中に落ちて",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/gensyounonakaniotite.png",
    id: 59,
  },
  {
    name: "生気に満ちた物語",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/seikinimitita.png",
    id: 60,
  },
  {
    name: "知られざる芸術",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sirarezarugeijutu.png",
    id: 61,
  },
  {
    name: "自業自得",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/zigouzitoku.png",
    id: 62,
  },
  {
    name: "デプレッション",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/depuressyon.png",
    id: 63,
  },
  {
    name: "ウォーク･アローン",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/walkalone.png",
    id: 64,
  },
  {
    name: "影にて",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kagenite.png",
    id: 65,
  },
  {
    name: "沈黙の眼差し",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tinmokunomanazasi.png",
    id: 66,
  },
  {
    name: "夜な夜な",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/yonayona.png",
    id: 67,
  },
  {
    name: "歯車の外",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/hagurumanosoto.png",
    id: 68,
  },
  {
    name: "昨日の出来事",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kinounodekigoto.png",
    id: 69,
  },
  {
    name: "新たなページ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/aratanapage.png",
    id: 70,
  },
  {
    name: "ティータイム",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/teatime.png",
    id: 71,
  },
  {
    name: "苦しい旅の途中",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kurusiitabinototyu.png",
    id: 72,
  },
  {
    name: "いざ出航",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/izasyukkou.png",
    id: 73,
  },
  {
    name: "アブサーディティ･ライフ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/abusadexitexi.png",
    id: 74,
  },
  {
    name: "サティスファイド･イーター",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/satexisufaido.png",
    id: 75,
  },
  {
    name: "楽しげな笑い声",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tanosigenawaraigoe.png",
    id: 76,
  },
  {
    name: "自由な心",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/ziyunakokoro.png",
    id: 77,
  },
  {
    name: "遥かなる前途",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/harukanaruzento.png",
    id: 78,
  },
  {
    name: "午後の休憩",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/gogonokyukei.png",
    id: 79,
  },
  {
    name: "むき出しの真実",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/mukidasinosinzitu.png",
    id: 80,
  },
  {
    name: "気ままに",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kimamani.png",
    id: 81,
  },
  {
    name: "明日も同じ",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/asumoonazi.png",
    id: 82,
  },
  {
    name: "思いを馳せて",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/omoiwohasete.png",
    id: 83,
  },
  {
    name: "静謐",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/seihitu.png",
    id: 84,
  },
  {
    name: "緑毒",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/ryokudoku.png",
    id: 85,
  },
  {
    name: "貪欲",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/donyoku.png",
    id: 86,
  },
  {
    name: "祟奉",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/tatari.png",
    id: 87,
  },
  {
    name: "航海",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/koukai.png",
    id: 88,
  },
  {
    name: "歓声",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/kannsei.png",
    id: 89,
  },
  {
    name: "無感覚",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/mukankaku.png",
    id: 90,
  },
  {
    name: "蒙昧",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/moumai.png",
    id: 91,
  },
  {
    name: "軽蔑",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/keibetu.png",
    id: 92,
  },
  {
    name: "鬱然",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/utuzen.png",
    id: 93,
  },
  {
    name: "喪失",
    level: 1,
    amplify: 0,
    owned: false,
    img: "images/sousitu.png",
    id: 94,
  },
];

